[packversionminrev]
	#Pack Minor Version Revision : X
	#Range: 0 ~ 32768
	minorrev = 0

[discord]
	#Enable Discord Rich Prescence
	discord = true

[packversionmin]
	#Pack Minor Version : X
	#Range: 0 ~ 32768
	minor = 0

[packversionmaj]
	#Pack Release Version Format : X
	#Range: 0 ~ 32768
	major = 1

[packmode]
	#ATM = 0 SLOP = 1 SKY = 2 MAGIC = 3 EXPERT = 4 GRAVITAS = 5
	#Range: 0 ~ 5
	enable = 0
